alias sudo='sudo '
alias ll='ls -hAlF'
ls --color=always &> /dev/null && alias ls='ls --color=always' || alias ls='ls -G'
alias grep='grep --color=auto'
alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias youtube-dl='yt-dlp'
alias gcp='git cherry-pick'
alias unrar='rar x'
alias json='python3 -m json.tool'
alias diff='diff --color=always'
alias git_reflog='git log --graph --oneline --reflog'

alias claude-ollama-q35-27b='"ollama launch claude --model qwen3.5:27b -- '
alias claude-ollama-q35-9b='ollama launch claude --model qwen3.5:9b -- '
alias claude-ollama-g4-e4b='ollama launch claude --model gemma4:e4b -- '
alias claude-ollama-q3-coder-30b='ollama launch claude --model qwen3-coder:30b -- '
alias claude-ollama-q36-35b-a3b='ollama launch claude --model qwen3.6:35b-a3b -- '
alias claude-ollama-q36-27b='ollama launch claude --model qwen3.6:27b -- '
#alias claude-ollama-q-agentworld-30b-m='ollama launch claude --model frob/qwen-agentworld:35b-a3b-ud-q4_K_M -- '
#alias claude-ollama-q-agentworld-30b-xl='ollama launch claude --model frob/qwen-agentworld:35b-a3b-ud-q6_K_XL -- '


alias claude-ollama-remote-q36-35b-a3b='CLAUDE_CODE_PROVIDER=ollama OLLAMA_HOST=http://ysera.local:11434 ollama launch claude --model qwen3.6:35b-a3b -- '
alias claude-ollama-remote-q-agentworld-30b-xl='CLAUDE_CODE_PROVIDER=ollama OLLAMA_HOST=http://ysera.local:11434 ollama launch claude --model kbatten/qwen-agentworld:35b-a3b-ud-q6_K_XL -- '

#alias claude='echo "tell app \"Terminal\" to set current settings of first window to settings set \"Claude\"" | osascript && claude '
#alias claude-ollama-q35-27b='echo "tell app \"Terminal\" to set current settings of first window to settings set \"CLQ35-27b\"" | osascript && ollama launch claude --model qwen3.5:27b -- '
#alias claude-ollama-q35-9b='echo "tell app \"Terminal\" to set current settings of first window to settings set \"CLQ35-9b\"" | osascript && ollama launch claude --model qwen3.5:9b -- '
#alias claude-ollama-g4-e4b='echo "tell app \"Terminal\" to set current settings of first window to settings set \"CLG4-e4b\"" | osascript && ollama launch claude --model gemma4:e4b -- '
#alias claude-ollama-q3-coder-30b='echo "tell app \"Terminal\" to set current settings of first window to settings set \"CLQ36-27b\"" | osascript && ollama launch claude --model qwen3-coder:30b -- '
#alias claude-ollama-q36-35b-a3b='echo "tell app \"Terminal\" to set current settings of first window to settings set \"CLQ36-35b-a3b\"" | osascript && ollama launch claude --model qwen3.6:35b-a3b -- '
#alias claude-ollama-q36-27b='echo "tell app \"Terminal\" to set current settings of first window to settings set \"CLQ36-27b\"" | osascript && ollama launch claude --model qwen3.6:27b -- '
#alias claude-ollama-q-agentworld-30b-m='echo "tell app \"Terminal\" to set current settings of first window to settings set \"CLQ36-27b\"" | osascript && ollama launch claude --model frob/qwen-agentworld:35b-a3b-ud-q4_K_M -- '
#alias claude-ollama-q-agentworld-30b-xl='echo "tell app \"Terminal\" to set current settings of first window to settings set \"CLQ36-27b\"" | osascript && ollama launch claude --model frob/qwen-agentworld:35b-a3b-ud-q6_K_XL -- '
