alias sudo='sudo '
alias ll='ls -hAlF'
ls --color=always &> /dev/null && alias ls='ls --color=always' || alias ls='ls -G'
alias grep='grep --color=auto'
alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias youtube-dl='yt-dlp'
alias gcp='git cherry-pick'
alias unrar='rar x'
alias json='python3 -m json.tool'
alias diff='diff --color=always'
alias git_reflog='git log --graph --oneline --reflog'
