#!/bin/bash

source ./script_lib/std.inc
source ./script_lib/install.inc
source ./script_lib/graphics.inc
source ./script_lib/link.inc


sudo dpkg --add-architecture i386
sudo apt-get update

sudo apt-get install -y wine winetricks

wine wineboot
xvfb-run winetricks -q win10 vcrun2015 cmd

download https://repo.anaconda.com/miniconda/Miniconda3-py38_23.3.1-0-Windows-x86_64.exe
install_exe Miniconda3-py38_23.3.1-0-Windows-x86_64.exe "/InstallationType=JustMe /AddToPath=1 /RegisterPython=1 /S"
