#!/bin/bash -e

source ./script_lib/std.inc
source ./script_lib/install.inc
source ./script_lib/graphics.inc

#sudo dpkg --add-architecture i386 && sudo apt-get update
sudo apt-get install -y wine winetricks

#export WINEPREFIX="$HOME/.wine32"
#export WINEARCH=win32
#wine wineboot

xvfb-run winetricks -q vcrun2008

download https://www.python.org/ftp/python/2.7.15/python-2.7.15.msi
install_msi python-2.7.15.msi
wine pip install pyinstaller numpy scipy ntfsutils

