#!/bin/bash -e

source ./script_lib/link.inc

mkdir ~/bin &> /dev/null && true

sudo apt-get install -y vim-nox rar mc

link_dotfiles .bash_aliases
link_dotfiles .gitconfig
link_dotfiles .gitignore
link_dotfiles .vimrc

link_bin bsync
link_bash_completion bsync

link_bin upgrayedd

if [[ -e ../profile_dirs ]] ; then
    link_bin_external ../profile_dirs/profile_dirs.py profile_dirs
else
    link_bin profile_dirs
fi

link_bin unjson_tool.py unjson

link_bin reencode-file
link_bin reencode
link_bin reencode-dirs

link_bin image-create
link_bin image-deploy


# personal git configurations, this is saved in .gitconfig, but here to show that it is being changed
git config --global init.defaultBranch main
git config --global core.pager cat
