#!/bin/bash -e

source ./script_lib/std.inc
source ./script_lib/install.inc
source ./script_lib/link.inc

name=go
version=1.25.5
filename="${name}${version}.linux-amd64.tar.gz"
remote="https://go.dev/dl/${filename}"

dirname="$(rootname "${filename}")"

download "${remote}" "${filename}"
install_go "${filename}"

link_bin_external "${HOME}/opt/${dirname}/bin/go"
link_bin_external "${HOME}/opt/${dirname}/bin/gofmt"

echo "finished $0"
