#!/bin/bash -e

source ./script_lib/std.inc
source ./script_lib/install.inc
source ./script_lib/link.inc

./install_dev_conda_win

download_github https://github.com/nagadomi/nunif

python3-venv-win -c iw3 pip install --upgrade setuptools


exit

pushd "${TANQ_DOWNLOAD_DIR}"/nunif

#sed -i.tmp -e 's/2\.7\.1+cu128/2.9.1+cu128/g' -e 's/0\.22\.1+cu128/0.24.1+cu128/' requirements-torch.txt
sed -i.tmp -e 's/2\.7\.1+cu128/2.7.1/g' -e 's/0\.22\.1+cu128/0.22.1/' requirements-torch.txt
rm -f requirements-torch.txt.tmp
python3-venv-win -c iw3 pip install -r requirements-torch.txt

sed -i.tmp 's/av==\(15.0.0\)$/--only-binary=:all: av==\1/g' requirements.txt
rm -f requirements.txt.tmp
python3-venv-win -c iw3 pip install -r requirements.txt

# TODO: instead of running a module, create iw3_download_models.py
#python3-venv-win -c iw3 python -m iw3.download_models

popd


echo "finished $0"
