#!/bin/bash -e

source ./script_lib/std.inc
source ./script_lib/install.inc
source ./script_lib/link.inc

FROM_SOURCE=1

if [[ $FROM_SOURCE -eq 0 ]] ; then
    sudo apt-get install -y ffmpeg
else
    sudo apt-get install -y nasm pkg-config libx264-dev libx265-dev build-essential libvidstab-dev libssl-dev libopus-dev

    mkdir -p "${TANQ_DOWNLOAD_DIR}" &> /dev/null
    cd "$TANQ_DOWNLOAD_DIR"
    if [[ -e FFmpeg ]] ; then
      cd FFmpeg
      git pull
    else
      git clone git@github.com:FFmpeg/FFmpeg.git
      cd FFmpeg
    fi

    export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/:$PKG_CONFIG_PATH
    ./configure --enable-gpl --enable-libx264 --enable-libx265 --enable-libvidstab --enable-openssl --enable-version3 --enable-libopus --prefix="$HOME/opt/ffmpeg"
    make
    make install

    link_bin_external "$HOME/opt/ffmpeg/bin/ffmpeg"
    link_bin_external "$HOME/opt/ffmpeg/bin/ffprobe"



    # install rust
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source "$HOME/.cargo/env"
    rustup update

    cd "$TANQ_DOWNLOAD_DIR"
    if [[ -e gifski ]] ; then
        cd gifski
        git pull
    else
        git clone git@github.com:ImageOptim/gifski.git
        cd gifski
    fi
    cargo build --release
    if [[ -e "$HOME/opt/gifski" ]] ; then
        rm -rf "$HOME/opt/gifski"
    fi
    cp -r "target/release" "$HOME/opt/gifski"
    link_bin_external "$HOME/opt/gifski/gifski"
fi

# loop a video to create both an audio version and a gif
#rm -f output.mp4 tout*.mp4 transforms.trf output.gif audio.m4a && \
#[[ ! -e audio.webm ]] && yt-dlp -o audio.webm --downloader ffmpeg --downloader-args "ffmpeg_i:-ss 10 -t 10.5" 1234 || true && \
#ffmpeg -i audio.webm -vn audio.m4a && \
#ffmpeg -i 5678.mp4 -filter_complex "[0:v]fps=30,format=yuv420p,split=2[vA][vB]; [vA]trim=0:9,setpts=PTS-STARTPTS[v0]; [vB]trim=0:1,setpts=PTS-STARTPTS[v1]; [v0][v1]xfade=transition=fade:duration=1:offset=8[v]" -map "[v]" -c:v libx264 -pix_fmt yuv420p -movflags +faststart toutput1.mp4 && \
#ffmpeg -i toutput1.mp4 -vf "vidstabdetect=shakiness=5:accuracy=15:result=transforms.trf" -f null - && \
#ffmpeg -i toutput1.mp4 -vf "vidstabtransform=input=transforms.trf:zoom=5:smoothing=30,unsharp=5:5:0.8:3:3:0.4" -c:v libx265 -crf 30 -preset veryslow toutput2.mp4 && \
#ffmpeg -i toutput2.mp4 -ss 5 -to 5.5 toutput3.mp4 && \
#ffmpeg -i toutput3.mp4 -f yuv4mpegpipe - | gifski -o output.gif - && \
#ffmpeg  -stream_loop 5 -i toutput3.mp4 -i audio.m4a output.mp4 && \
#rm -f tout*.mp4 transforms.trf
