#!/bin/bash -e

source ./script_lib/std.inc
source ./script_lib/link.inc
source ./script_lib/install.inc

mkdir ~/bin &> /dev/null && true

$SUDO apt-get install -y vim-nox unrar mc nfs-common tmux git build-essential gpg

bashrc_export_variable bash_editor EDITOR=vi
bashrc_export_variable sudo SUDO=$SUDO
bashrc_export_variable user_bin PATH=${HOME}/bin:\$PATH
bashrc_source_script "link_bash_aliases" "$HOME/.bash_aliases"

link_dotfiles .bash_aliases
link_dotfiles .gitconfig
link_dotfiles .gitignore
link_dotfiles .vimrc

link_bin bsync
link_bash_completion bsync

link_bin upgrayedd

upgrayedd -y

if [[ -e ../profile_dirs ]] ; then
    link_bin_external ../profile_dirs/profile_dirs.py profile_dirs
else
    link_bin profile_dirs
fi

link_bin unjson_tool.py unjson

link_bin reencode-file
link_bin reencode
link_bin reencode-dirs

link_bin image-create
link_bin image-deploy

link_bin audiobook-decode

link_bin delta2time

# personal git configurations, this is saved in .gitconfig, but here to show that it is being changed
git config --global init.defaultBranch main
git config --global core.pager cat
git config --global --replace-all --bool push.autoSetupRemote true

echo "finished $0"
