#!/bin/bash -e

source ./script_lib/std.inc
source ./script_lib/install.inc
source ./script_lib/link.inc

name="yt-dlp"
version=2025.12.08
filename="${name}.${version}.zip"
remote="https://github.com/yt-dlp/yt-dlp/releases/download/${version}/yt-dlp_linux.zip"

dirname="$(rootname "${filename}")"

download "${remote}" "${filename}"
install_ytdlp ${filename}

curl -fsSL https://deno.land/install.sh | sh

link_bin_external "${HOME}/opt/${dirname}/yt-dlp_linux" "yt-dlp"

yt-dlp -U

echo "finished $0"
