#!/bin/bash -e

source ./script_lib/std.inc
source ./script_lib/install.inc
source ./script_lib/link.inc

./install_dev_python_win

download_github https://github.com/nagadomi/nunif

python3-venv-win -c iw3 pip install --upgrade setuptools

# install https://wiki.python.org/moin/WindowsCompilers
# https://visualstudio.microsoft.com/vs/older-downloads/#microsoft-build-tools-2015
#download https://download.microsoft.com/download/5/F/7/5F7ACAEB-8363-451F-9425-68A90F98B238/visualcppbuildtools_full.exe

pushd "${TANQ_DOWNLOAD_DIR}"/nunif
python3-venv-win -c iw3 pip install -r requirements-torch.txt
sed -itmp 's/av==\(15.0.0\)$/--only-binary=:all: av==\1/g' requirements.txt
rm -f requirements.txt.tmp
python3-venv-win -c iw3 pip3 install -r requirements.txt
popd

exit

python -m iw3.download_models

echo "finished $0"
