#!/bin/bash -e

source ./script_lib/std.inc
source ./script_lib/install.inc

install_wine
wineboot

install_wine_java8

download https://download.videohelp.com/r0lZ/BD3D2AVS/BD3D2MK3D.7z

# https://www.mediafire.com/folder/x6f7yqjufdg7c/Groucho's_Avisynth_Stuff
# https://www.mediafire.com/file/lpn7r702r38l3k6/UniversalAvisynthInstaller_20210119.7z/file

download "https://www.mediafire.com/file/lpn7r702r38l3k6/UniversalAvisynthInstaller_20210119.7z/file"

# remove admin check from save and force 9 for x86
sed -i.tmp -e 's/if errorlevel 1 goto :noAdmin//g' -e 's/set \/p no=.*/set no=9/g' -e 's/pause//g' "${TANQ_DOWNLOAD_DIR}/UniversalAvisynthInstaller_20210119/AvisynthRepository/setavs.cmd"
rm -f "${TANQ_DOWNLOAD_DIR}/UniversalAvisynthInstaller_20210119/AvisynthRepository/setavs.cmd.tmp"

wine "${TANQ_DOWNLOAD_DIR}/UniversalAvisynthInstaller_20210119/AvisynthRepository/setavs.cmd"

# wine BD3D2MK3D/BD3D2MK3D/BD3D2MK3D.exe


