#!/bin/bash -e

source ./script_lib/std.inc
source ./script_lib/install.inc
source ./script_lib/link.inc

FROM_SOURCE=1

if [[ $FROM_SOURCE -eq 0 ]] ; then
    sudo apt-get install -y ffmpeg
else
    sudo apt-get install -y nasm pkg-config libx264-dev libx265-dev build-essential libvidstab-dev

    mkdir -p "${TANQ_DOWNLOAD_DIR}" &> /dev/null
    cd "$TANQ_DOWNLOAD_DIR"
    if [[ -e FFmpeg ]] ; then
      cd FFmpeg
      git pull
    else
      git clone git@github.com:FFmpeg/FFmpeg.git
      cd FFmpeg
    fi

    export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/:$PKG_CONFIG_PATH
    ./configure --enable-gpl --enable-libx264 --enable-libx265 --enable-libvidstab --enable-openssl --prefix="$HOME/opt/ffmpeg"
    make
    make install

    link_bin_external "$HOME/opt/ffmpeg/bin/ffmpeg"
    link_bin_external "$HOME/opt/ffmpeg/bin/ffprobe"
fi
