#!/bin/bash -e

# link basic dotfiles
function link_dotfiles() {
  ln -s -f "$PWD/dotfiles/$@" "$HOME/$@"
}

# link dev bins
function link_bin() {
  ln -s -f "$PWD/bin/$@" "$HOME/bin/$@"
}

link_dotfiles .bash_aliases
link_dotfiles .gitconfig
link_dotfiles .gitignore
link_dotfiles .vimrc

link_bin profile_dirs
