#!/bin/bash -e

source ./script_lib/link.inc

link_dotfiles .bash_aliases
link_dotfiles .gitconfig
link_dotfiles .gitignore
link_dotfiles .vimrc

link_bash_completion

link_bin bsync

if [[ -e ../profile_dirs ]] ; then
    link_bin_external ../profile_dirs/profile_dirs.py profile_dirs
else
    link_bin profile_dirs
fi

link_bin unjson_tool.py unjson
