#!/bin/bash -e

# set up a deluge windows dev environment


if [[ -n "$SCRIPTS_SETUP_DEV_DELUGE_WIN" ]] ; then
    return
fi
SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# dependencies
source "${SCRIPTPATH}/setup_dev_python_win"


RUNALL=true
if $RUNALL ; then
echo "*packages"
package_install subversion

echo "*pip"
pip_install_win wheel
pip_install_win twisted
pip_install_win cryptography
pip_install_win pyopenssl
pip_install_win service_identity
pip_install_win chardet
pip_install_win mako
pip_install_win pyxdg
pip_install_win slimit
fi


cleanup
export SCRIPTS_SETUP_DEV_DELUGE_WIN=1
