#!/bin/bash -e

# set up a python windows dev environment


if [[ -n "$SCRIPTS_SETUP_DEV_WIN" ]] ; then
    return
fi
SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# dependencies
source "${SCRIPTPATH}/setup_dev_python"
source "${SCRIPTPATH}/setup_dev_win"


pip_install_win() {
    local package=
    for package in $@ ; do
        echo " ${package}" | tee -a "${LOGFILE}"
        xvfb-run wine "C:\\Python27\\python.exe" -m pip install "${package}" >> "${LOGFILE}" 2>&1

        local package_test=${package}
        if [[ "${package}" == "pillow" ]] ; then
            package_test="PIL"
        elif [[ "${package}" == "PyOpenGL" || "${package}" == "PyOpenGL_accelerate" ]] ; then
           package_test="OpenGL"
        elif [[ "${package}" == "pyopenssl" ]] ; then
            package_test="OpenSSL"
        elif [[ "${package}" == "pyxdg" ]] ; then
            package_test="xdg"
        elif [[ "${package}" == "twisted" ]] ; then
            # fix a problem where pyinstaller doesn't pick up zope.interface
            touch ${HOME}/.wine/drive_c/Python27/Lib/site-packages/zope/__init__.py
        fi

        wine "C:\\Python27\\python.exe" -c "$(echo -e "try:\n  import ${package_test}\nexcept ImportError as e:\n  raise e\nexcept Exception:\n  pass\n")" >> "${LOGFILE}" 2>&1
        set_rvalue "${package}"
    done
}


RUNALL=true
if $RUNALL; then
echo "*other"
fetch_and_install "https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi"
fetch_and_install "http://downloads.sourceforge.net/project/pywin32/pywin32/Build%20219/pywin32-219.win32-py2.7.exe"
fetch_and_install "http://downloads.sourceforge.net/project/numpy/NumPy/1.8.1/numpy-1.8.1-win32-superpack-python2.7.exe"
fetch_and_install "http://downloads.sourceforge.net/project/scipy/scipy/0.14.0/scipy-0.14.0-win32-superpack-python2.7.exe"
fetch_and_install "http://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi"

echo "*bin"
file_install "dev_python_win/python-win" ~/bin
file_install "dev_python_win/pyinstaller-win" ~/bin

echo "*pip"
pip_install_win pillow
pip_install_win ntfsutils
pip_install_win speech
pip_install_win PyOpenGL PyOpenGL_accelerate
pip_install_win markdown
pip_install_win twisted

echo "*other"
echo " freeglut"
fetch_and_install "http://files.transmissionzero.co.uk/software/development/GLUT/freeglut-MSVC.zip"
\cp ${HOME}/opt/freeglut-MSVC/bin/freeglut.dll ~/.wine/drive_c/Python27/Lib/site-packages/OpenGL/DLLS/ &> /dev/null
fetch_and_install "http://pygame.org/ftp/pygame-1.9.1.win32-py2.7.msi"
fi


cleanup
export SCRIPTS_SETUP_DEV_WIN=1
