#!/bin/bash

# set up a python windows dev environment


function pip_install_win {
    for package in $@ ; do
        echo " ${package}" | tee -a "${LOGFILE}"
        wine "C:\Python27\Scripts\pip.exe" install "${package}" >> "${LOGFILE}" 2>&1

        local package_test=${package}
        if [[ "${package}" == "PyOpenGL" || "${package}" == "PyOpenGL_accelerate" ]] ; then
            local package_test="OpenGL"
        fi

        wine "C:\Python27\python.exe" -c "$(echo -e "try:\n  import ${package_test}\nexcept ImportError as e:\n  raise e\nexcept Exception:\n  pass\n")" >> "${LOGFILE}" 2>&1
        set_rvalue "${package}"
    done
}

function easy_install_win {
    local package=${1}

    echo " $package"
    PYTHONDONTWRITEBYTECODE= wine "C:\Python27\Scripts\easy_install.exe" "${package}" &> /dev/null
}


# includes
SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${SCRIPTPATH}/setup_dev_python"
source "${SCRIPTPATH}/setup_dev_win"


if [[ "${BASH_SOURCE}" == "${0}" ]] ; then
    echo "setting up..."

    mkdir ${DOWNLOADDIR} &> /dev/null


    echo "*packages"
    package_update
    package_install git
    package_install python-pip
    package_install xvfb
    package_install ttf-mscorefonts-installer
    package_install wine1.4
    package_install wine1.4-dev
    package_install p7zip


    echo "*winetricks"
    winetricks_install vcrun2008


    echo "*pip"
    pip_install virtualenv


    echo "*other"
    fetch_and_install "http://www.python.org/ftp/python/2.7.3/python-2.7.3.msi"
    fetch_and_install "http://downloads.sourceforge.net/project/pywin32/pywin32/Build%20218/pywin32-218.win32-py2.7.exe"
    fetch_and_install "http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11.win32-py2.7.exe"
    fetch_and_install "http://effbot.org/downloads/PIL-1.1.7.win32-py2.7.exe"

    # fix bug in 1.1.7 _imagingft.pyd
    f=$(mktemp)
    head -c 387025 ${HOME}/.wine/drive_c/Python27/Lib/site-packages/PIL/_imagingft.pyd > ${f}
    echo -n "!--" >> ${f}
    tail -c +387029 ${HOME}/.wine/drive_c/Python27/Lib/site-packages/PIL/_imagingft.pyd | head -c 246 >> ${f}
    echo -n "--" >> ${f}
    tail -c +387277 ${HOME}/.wine/drive_c/Python27/Lib/site-packages/PIL/_imagingft.pyd >> ${f}
    \mv ${f} ${HOME}/.wine/drive_c/Python27/Lib/site-packages/PIL/_imagingft.pyd

    fetch_and_install "http://downloads.sourceforge.net/project/scipy/scipy/0.12.0b1/scipy-0.12.0b1-win32-superpack-python2.7.exe"

    echo " pyinstaller-win"
    fetch_and_install "https://github.com/pyinstaller/pyinstaller/tarball/develop" "pyinstaller-dev.tar.gz" "pyinstaller-dev" "ln -sfT \$(pwd)/pyinstaller.py ${HOME}/bin/pyinstaller &> /dev/null"
    echo '#!/bin/bash
pyinstaller_dir=$(dirname "$(readlink ~/bin/pyinstaller)")
PYTHONPATH=${PYTHONPATH}:"${pyinstaller_dir}"
wine "C:\\Python27\\python.exe" "${pyinstaller_dir}/pyinstaller.py" -c -F "${@}"' > ~/bin/pyinstaller-win
    chmod 755 ~/bin/pyinstaller-win


    echo "*easy_install"
    easy_install_win pip
    easy_install_win numpy


    echo "*pip"
    pip_install_win ntfsutils
    pip_install_win speech
    pip_install_win PyOpenGL PyOpenGL_accelerate


    echo "*other"
    echo " freeglut"
    fetch_and_install "http://files.transmissionzero.co.uk/software/development/GLUT/freeglut-MSVC.zip"
    \cp ${HOME}/opt/freeglut-MSVC/bin/freeglut.dll ~/.wine/drive_c/Python27/Lib/site-packages/OpenGL/DLLS/ &> /dev/null


    cleanup
fi
