#!/bin/bash -e

# set up a deluge dev environment


if [[ -n "$SCRIPTS_SETUP_DEV_DELUGE" ]] ; then
    return
fi
SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# dependencies
source "${SCRIPTPATH}/setup_dev_python"


RUNALL=true
if $RUNALL ; then
echo "*packages"
package_install subversion
package_install python-gtk2
package_install python-glade2
package_install python-libtorrent

echo "*pip"
pip_install wheel
pip_install twisted
pip_install cryptography
pip_install pyopenssl
pip_install service_identity
pip_install chardet
pip_install mako
pip_install pyxdg
pip_install slimit
fi


cleanup
export SCRIPTS_SETUP_DEV_DELUGE=1
