#!/bin/bash

create=0
if [[ "${1}" == "-c" ]] ; then
    create=1
    shift
fi

if [[ ! -f ~/.virtualenvs/${1}/bin/activate ]] ; then
    if [[ ${create} -eq 1 ]] ; then
        mkdir ~/.virtualenvs &> /dev/null
        pushd . &> /dev/null
        cd ~/.virtualenvs
        unset PYTHONDONTWRITEBYTECODE
        virtualenv --system-site-packages ${1}
        popd &> /dev/null
    else
        echo "env \"${1}\" not found"
        exit
    fi
fi

source ~/.virtualenvs/${1}/bin/activate
shift
${@}
