#!/bin/bash -e

source ./script_lib/std.inc
source ./script_lib/install.inc

./install_dev_conda_win llama-setup

download_github kbatten/llama-setup
pushd "${TANQ_DOWNLOAD_DIR}/llama-setup"
python3-venv-win -c llama-setup pip install -r requirements.txt
popd

sleep 1
echo "# build zimageturbo-server.py"
echo
echo "pyinstaller-win --venv llama-setup --metadata requests --packages transformers zimageturbo-server.py"
