#!/bin/bash -e

source ./script_lib/std.inc
source ./script_lib/install.inc

./install_dev_conda_win llama-setup

download_github kbatten/llama-setup
pushd "${TANQ_DOWNLOAD_DIR}/llama-setup"
python3-venv-win -c llama-setup pip install -r requirements.txt
python3-venv-win -c llama-setup pip install -r requirements-boogu-server.txt
popd

echo "# build zimageturbo-server.py"
echo "pyinstaller-win --venv llama-setup --metadata requests --collect-all transformers --collect-submodules torch --collect-all scipy --add-data \"gallery;gallery\" zimageturbo-server.py"
echo
echo "# build boogu-server.py"
echo "ln -s ../Boogu-Image/boogu ."
echo "pyinstaller-win --venv llama-setup --metadata requests --collect-all transformers --collect-submodules torch --collect-all scipy --add-data \"gallery;gallery\" \"boogu;boogu\" boogu-server.py"
