#!/bin/bash

source ./script_lib/std.inc
source ./script_lib/install.inc

./install_dev_python_win

python3-venv-win -c ntfs pip install ntfsutils

if [[ -e "$HOME/.wine/drive_c/users/$USER/.virtualenvs/ntfs/Lib/site-packages/ntfsutils-0.1.5.dist-info" ]] ; then
    apply_patch "ntfutils.patch" "$HOME/.wine/drive_c/users/$USER/.virtualenvs/ntfs/Lib/site-packages/"
fi

# pyinstaller-win --venv ntfs -- --uac-admin linkssd.py
# pyinstaller-win --venv ntfs profile_dirs.py
