#!/bin/bash

CUDA=11.8

./install_dev_conda_win

cd ~/src/DragGAN
git checkout environment.yml

sed -i 's/^  - nvidia/  - nvidia\n  - conda-forge/g' environment.yml
sed -i 's/dependencies:/dependencies:\n  - pyinstaller/g' environment.yml
sed -i 's/\(^.*pytorch.*=.*$\)/\1\n  - pytorch-cuda='"${CUDA}"'/g' environment.yml
sed -i 's/^  - cudatoolkit=.*$/  - cudatoolkit='"${CUDA}"'/g' environment.yml

wine conda env create -f environment.yml
wine conda info
wine conda env list

sed -i 's/(result, consumed) = self\._buffer_decode(data, self\.errors, final)/(result, consumed) = self._buffer_decode(data, "replace", final)/g' ${HOME}/.wine/drive_c/users/${USER}/miniconda3/envs/stylegan3/lib/codecs.py

echo "make sure to install nvidia cuda tools version ${CUDA}"
echo "git clean -dfx && wine cmd /c conda activate stylegan3 \"&&\" pyinstaller --onedir visualizer_drag.py"
echo "wine cmd /c conda activate stylegan3 \"&&\" python -m compileall -b training"
echo "copy ${HOME}/.wine/drive_c/users/${USER}/miniconda3/envs/stylegan3/lib/site-packages/glfw/glfw3.dll"
echo "copy ${HOME}/.wine/drive_c/users/${USER}/miniconda3/envs/stylegan3/Library/bin/ninja.exe"
echo "copy ${HOME}/.wine/drive_c/users/${USER}/miniconda3/envs/stylegan3/include"
echo "copy ${HOME}/.wine/drive_c/users/${USER}/miniconda3/envs/stylegan3/libs"
echo "copy checkpoints"
echo "copy training"

# git@github.com:XingangPan/DragGAN.git
