#!/bin/bash -e

# set up a windows dev environment


if [[ -n "$SCRIPTS_SETUP_DEV_WIN" ]] ; then
    return
fi
SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# dependencies
source "${SCRIPTPATH}/setup_base"


winetricks_install() {
    local trick=${@}

    echo " ${trick}"
    echo "xvfb-run winetricks -q ${trick}" >> ${LOGFILE}
    # workaround -q not suppressing a mono related message
    xvfb-run winetricks -q ${trick} >> ${LOGFILE} 2>&1 &
    pid=$!
    sleep 1
    local i=0
    while ps -p $pid &> /dev/null ; do
        sleep 1
        i=$((i+1))
        if [[ $i -gt 40 ]] ; then
            pkill -9 -f install_mono || true
        else
            pkill -f install_mono || true
        fi
    done
    wait
}


RUNALL=true
if $RUNALL; then
echo "*packages"
package_install xvfb
#package_install ttf-mscorefonts-installer
package_install wine
package_install winetricks
package_install imagemagick

echo "*bin"
file_install "dev_win/xvfb-grab" ~/bin
file_install "dev_win/autoit-win" ~/bin
file_install "dev_win/autohotkey-win" ~/bin

echo "*winetricks"
winetricks_install vcrun2008

echo "*other"
fetch_and_install "https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe" "" "" "/S"
fetch_and_install "http://ahkscript.org/download/ahk-install.exe" "" "" "/S"
fi


cleanup
export SCRIPTS_SETUP_DEV_WIN=1
