#!/bin/bash -e

# set up a python dev environment


if [[ -n "$SCRIPTS_SETUP_DEV_PYTHON" ]] ; then
    return
fi
SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# dependencies
source "${SCRIPTPATH}/setup_base"


pip_install() {
    for package in $@ ; do
        echo " ${package}" | tee -a "${LOGFILE}"
        sudo pip install "${package}" >> "${LOGFILE}" 2>&1

        local package_test=${package}
        if [[ "${package}" == "pyopenssl" ]] ; then
            package_test="OpenSSL"
        elif [[ "${package}" == "pyxdg" ]] ; then
            package_test="xdg"
        fi

        python -c "$(echo -e "try:\n  import ${package_test}\nexcept ImportError as e:\n  raise e\nexcept Exception:\n  pass\n")" >> "${LOGFILE}" 2>&1
        set_rvalue "${package}"
    done
}


RUNALL=true
if $RUNALL; then
echo "*packages"
package_install python-pip
package_install python-dev
package_install python-pygame
package_install python-opencv
package_install python-scipy
package_install python-numpy
package_install python-imaging

echo "*pip packages"
pip_install virtualenv
pip_install requests
pip_install flask
pip_install twisted
pip_install sh
pip_install pep8
pip_install pylint

echo "*other"
fetch_and_install "https://pypi.python.org/packages/source/P/PyInstaller/PyInstaller-2.1.tar.gz" "" "" "ln -sfT \$(pwd)/pyinstaller.py ${HOME}/bin/pyinstaller &> /dev/null ; chmod 755 \$(pwd)/pyinstaller.py"

echo "*bashrc"
set_variable "PYTHONDONTWRITEBYTECODE" "true"

echo "*bin"
file_install "dev_python/pylint-pep8" ~/bin
file_install "dev_python/pyvirt" ~/bin
fi


cleanup
export SCRIPTS_SETUP_DEV_PYTHON=1
