#!/bin/bash


# it seems that return values from go * doesn't indicate success/failure of tests
result=0

echo "==== fmt ====="
go fmt
#for d in $(\ls) ; do pushd $d && go fmt ; popd &> /dev/null ; done
for d in $(\ls) ; do (cd $d &> /dev/null && go fmt) ; done
echo

echo "==== test ===="
ls *test.go &> /dev/null && go test
echo

echo "==== race ===="
ls *test.go &> /dev/null && go test -race
for f in $(\ls *.go) ; do grep "^package main" $f && go run -race $f $@ ; done
echo

echo "==== vet ====="
go vet
echo

echo "==== lint ===="
# go get github.com/golang/lint/golint
for f in $(find . -name "*.go") ; do golint $f ; done
echo


# github.com/remyoudompheng/go-misc/deadcode
# github.com/kisielk/errcheck
# gocov || go test -cover


# TODO: tests and examples should be in package: foo_test
# TODO: remove panics, add new type of error. or if panic is the right decision, document why it can heppen
# TODO: add benchmarks


exit ${result}
